name: Send Email

on:
  push:
    branches:
      - sendEmail
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up environment variables
      run: |
        BUILD_NUMBER=Hi $(printf '%03d' ${{ github.run_number }})
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
        echo "BUILD_NUMBER is $BUILD_NUMBER"
      

    # - name: Send mail
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     # connection_url: ${{secrets.MAIL_CONNECTION}}
    #     server_address: smtp.gmail.com
    #     server_port: 465
    #     secure: true
    #     username: ${{secrets.MAIL_USERNAME}}
    #     password: ${{secrets.MAIL_PASSWORD}}
    #     subject: "Resume Update #${BUILD_NUMBER} [Utsav Chaudhary]"

    #     to: utsavmaan28@gmail.com
    #     from: Utsav Chaudhary
    #     body: |
    #       Hey, this is the new resume update for Utsav Chaudhary. 
    #       Please find the resume in the attachments!
          
    #       Thanks & Regards
    #       Utsav Chaudhary
    #     attachments: ./makeResume/static/*.pdf
