name: Send Email Workflow

on:
  push:
    branches:
      - sendEmail
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Run email sending script
    #   run: python path/to/your_email_script.py

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        # username: ${{secrets.MAIL_USERNAME}}
        # password: ${{secrets.MAIL_PASSWORD}}
        # subject: Resume Update 00 [Utsav Chaudhary]
        # to: obiwan@example.com,yoda@example.com
        # from: Luke Skywalker # <user@example.com>
        # body: Build job of ${{github.repository}} completed successfully!
        # attachments: attachments.zip,git.diff,./dist/static/*.js


        subject: Resume Update 00 [Utsav Chaudhary]
        to: sample1test.it2@gmail.com
        from: Luke Skywalker <user@example.com>
        body: Build job of ${{ github.repository }} completed successfully!
        attachments: ./makeResume/static/*.pdf
